# Author: Abdelrahman Hany
# Created On: 18-Feb-2022

name: Python application

on:
  push:
    branches: [ beta ]
    
jobs:
  buildAndRun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f API/requirements.txt ]; then pip install -r API/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        cd API
        python run.py &
        PID=$!
        sleep 5
        kill $PID
    
    
  deploy:
    needs: [buildAndRun]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_AUTH_TOKEN }}
        heroku_email: ${{ secrets.MAIL }}
        heroku_app_name: signature-based-detection-api
        appdir: "API"

  mergeToMain:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge staging -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}